taskcluster/taskcluster-docs

- docker-worker/index.md
> Add docs for the docker-worker proxy feature

- _config.yml
- queue/worker-interaction/index.md
New proposal for worker interaction...
> New worker interaction

- docker-worker/index.md
> Better docs on enc env vars

- workers/generic-worker/index.md
Relocated github.com/petemoore/generic-worker => github.com/taskcluster/generic-worker
> petemoore/generic-worker => taskcluster/generic-worker (gh-pages)

- presentations/index.md
Once merged, I can also push to gh-pages branch.
> Added youtube video to presentations section

- workers/docker-worker/index.md
Don't merge this yet, will add cacheSave documentation soon.
> Docker save v2

- learn/authenticate/index.md
- learn/create-task/index.md
- learn/index.md
some typo fixes for the tutorial and little changes
> Learn update

- workers/docker-worker/index.md
Adding the interactive feature to docs. Maybe hold on merge until when interactive is actually moved onto the more common amis.
> Interactive

- _config.yml
- services/taskcluster-github/index.md
Some more work needs to be done on the taskclusterrc schema; but these changes will be picked up by the docs without modifying them.
> Add taskcluster github docs

- _config.yml
- devel/namespaces/index.md
Discussion is welcome here -- I'm not sure I'm right everywhere!
I'm trying to document what's in place now, rather than the way I'd like it to be.  We can adjust later.
> Bug 1219943: document namespaces

- presentations/TC-101/index.html
- presentations/TC-101/slides/high-level-arch.md
- presentations/TC-101/slides/migration-roadmap.md
- presentations/TC-101/slides/tc-roadmap.md
- presentations/TC-101/slides/what-is-task.md
- presentations/TC-101/slides/what-is-tc.md
- presentations/TC-101/slides/why-tc.md
first pass... :)
Mostly reused @jonasfj's intro slides.
> selena's intro slides

- _config.yml
Link to travis CI view of our vcs projects.
> Added CI link for taskcluster components

- devel/namespaces/index.md
Added this as I think we can agree to anyone under NDA.
I just wanted to be more clear here... As I'm granting the scope to b2g QA.
> Trying to specify private/* more

- workers/docker-worker/index.md
@dividehex I'd love your feedback too..
> Add discussion of coalescing

- devel/namespaces/index.md
Before I go implementing this, does this division look OK?
> Bug 1220684: namespaces for worker caches

- presentations/TC-102/slides/tc-clients/02.md
The canonical URLs are https://...
> Correct Treeherder name and URL

- auth/authorized-scopes/index.md
I'm not 100% sure about this one, please confirm before merging.
> Fix authorized scope reference

- introduction/getting-started/index.md
afaict this command is the correct one. I'm guessing this was changed at some point?
> Update mach command in intro

- services/taskcluster-github/index.md
Docs for https://github.com/taskcluster/taskcluster-github/pull/40
> Add section about branch filtering to Taskcluster-Github docs.

- README.md
- _config.yml
- _layouts/default.html
- assets/docref/reference.ejs
- assets/docref/stability.css
This PR builds on top of the work @kraldav has done in [bug 1222982](https://bugzilla.mozilla.org/show_bug.cgi?id=1222982).
> Bug 1222982 - API docs should show API stability

- _layouts/default.html
This isn't pretty, but it seems to work and should be good enough for now until we can have new docs site generation. This change is necessary to add search.
> Hack to make active sections work

- src/manual/apis/roles.md
This should help clear up some potential confusion, especially about the two different ways stars can be involved in roles.
> Bug 1226252: fill out roles docs

- layout/navbar.pug
- layout/sidebar.pug
- src/assets/style.css
This allows us to be indexed again and cleans up the sidebar nav a bit (to the best of my limited front-end abilities).
> Make sections active for the return of search

- src/reference/libraries/azure-entities/index.md
- src/reference/libraries/index.md
:heart: this `data-doc-readme` thing :)
> Add azure entities README

- src/reference/libraries/taskcluster-lib-monitor/index.md
- src/reference/libraries/taskcluster-lib-validate/index.md
Not much beyond the title for this one.
> Add tc-lib-{validate,monitor} to libraries docs

- src/reference/core/treeherder/exchanges.md
> Added treeherder exchanges to references section

- src/assets/docreadme/docreadme.js
> fix mix content

- src/reference/core/treeherder/index.md
- src/reference/core/treeherder/task-treeherder-config.md
- src/tutorial/gecko-decision-task.md
- src/tutorial/gecko-new-job.md
- src/tutorial/gecko-task-graph.md
- src/tutorial/gecko-tasks.md
One of these links (how-tos.html) doesn't work yet, but will when bug 1281004 lands.
> Update tutorial regarding treeherder and in-tree config

- src/manual/vcs/github.md
Changed ubuntu image to node.js image in all the snippets (except last one). Changed the paragraph on ubuntu image to paragraph on node image. Changed the command line in the first snippet. In the same snippet, added a comment with a note on indentation. Adjusted indentation a bit, to make it visually clearer.
> Update image references, add note on indentation

- src/manual/3rdparty/index.md
I wrote this in the process of thinking about [bug 1278986](https://bugzilla.mozilla.org/show_bug.cgi?id=1278986).
> Add some text about confused deputies

- src/manual/devel/namespaces.md
This really just reflects the current consensus.
> Bug 1220686: document worker types

- src/manual/integrations/github.md
> Releases added

- src/manual/integrations/github.md
Hey @djmitche @imbstack  can you take a look at this? Thanks!
> GitHub tokens and env vars

- src/manual/integrations/github.md
This is the associated doc change for taskcluster/taskcluster-github#100.
Thanks!
> Doc changes for taskcluster/taskcluster-github#100

- src/manual/integrations/apis/authn.md
- src/manual/integrations/apis/authorized-scopes.md
- src/manual/integrations/apis/clients.md
- src/manual/integrations/apis/errors.md
- src/manual/integrations/apis/index.md
- src/manual/integrations/apis/roles.md
- src/manual/integrations/apis/scopes.md
- src/manual/integrations/apis/signed-urls.md
- src/manual/integrations/apis/temporary-credentials.md
Docs for https://bugzilla.mozilla.org/show_bug.cgi?id=1330978 and taskcluster/taskcluster-lib-api#51
> Add docs on API errors

- src/reference/workers/docker-worker/features.md
Anybody can review this. Please land it if it makes sense to you.
> Correct the baseUrl in client

- redirects.yml
> Fixes queue redirect, hopefully

- layout/footer.pug
- layout/sidebar.pug
- lib/navlinks.js
- lib/raw.js
- src/assets/style.css
This makes the TOC a bit more navigable in the new world we have with docs and such. It [looks ok](https://imbstack.keybase.pub/newdocstoc.mov) to me, but certainly isn't perfect. The css in particular is probably done in a boneheaded way, but it seems good enough for the docs site for now?
> Make table of contents nicer

- src/manual/devel/best-practices/microservices.md
@gregarndt for the papertrail bit
@imbstack for the naming bit -- I've already started to do this with the docs site after all!
> Best practice fixes

- gulpfile.js
- redirects.yml
- src/manual/integrations/apis/index.md
This makes taskcluster-client.py different from taskcluster-client :)
> Keep .py extension

- src/assets/style.css
https://bugzilla.mozilla.org/show_bug.cgi?id=1352779
> Bold indicates required properties

- layout/reference.pug
- lib/raw.js
- package.json
- yarn.lock
This code is ugly as sin, but I'm tired of looking at it. I _think_ it handles just about every case of json-schema. I'm sure there are some things I've left out, but it seems to get pretty close. This can't be landed until taskcluster/taskcluster-login#49 is landed, but then it should Just Work™.
If we'd like this code to be nicer I can circle back to this soon and do a cleanup pass. Ping me if you'd like an ngrok link.
> Render schemas at compile time

- gulpfile.js
- package.json
- src/manual/tasks/actions/index.md
- src/manual/tasks/actions/schema.yml
- src/manual/tasks/actions/spec.md
- src/manual/tasks/actions/ui.md
- yarn.lock
> Add actions spec to manual

- src/manual/design/namespaces.md
A few undocumented namespaces we should document...
> GitHub index namespace

- .taskcluster.yml
- package.json
This is a temporary fix until yarn 1.0.0 is actually released
> Make yarn fail on network errors less

- src/people.pug
For https://github.com/taskcluster/json-e/pull/178 and upcoming work :)
> Add anejaalisha to people

- src/people.pug
> Add prachi1210

- src/tutorial/hello-world.md
> hello-world task is now in YAML

- src/manual/design/namespaces.md
for projects with lots of custom hardware provisioned workerTypes...
> Project namespacing for provisionerId

- src/manual/design/devel/best-practices/microservices.md
I might've missed something. Just let me know!
> Update best practices for new node and lint

- src/manual/design/devel/best-practices/commits.md
Docs to use as a reference when creating commit messages.
> Instructions for commit messages

- src/manual/design/devel/best-practices/commits.md
Wrote a simple blog post w.r.t sequences of commits to help contributors.
Refers to:  https://github.com/taskcluster/taskcluster-rfcs/issues/101
> Add 'sequences of commits' in recommended readings

- src/people.pug
https://mozillians.org/en-US/u/ydidwania/
> Add ydidwania

- .taskcluster.yml
- layout/reference.pug
- package.json
Note: This is not pretty yet! We can focus on that bit collectively in this review if the general idea makes sense or I can go back to the drawing board!
This is for taskcluster/taskcluster-rfcs#23
> Render scope expressions

- src/manual/design/namespaces.md
Not sure if this is still an up-to-date list of login providers - let me know what you think. Thanks!
> Bug 1436002 - documented artifact namespace <taskcluster-login_identity>/*

- layout/reference.pug
I _think_ this is all we need to update. The raw string thing already worked. Anything else you can think of?
> Add "else" to scope expressions

- src/manual/using/integration/frontend.md
Do not merge yet.
Will be ready for merge when:
> Bug 1437116 - Change "full-user-credentials" scope to "taskcluster-credentials"

- layout/footer.pug
- layout/head.pug
- layout/navbar.pug
- lib/nginx-site.conf.ejs
Is there any algolia account we should cancel, or anything like that?
> Bug 1452188 - remove third-party search

- src/resources.md
> Remove dead link to planet

- src/manual/design/devel/best-practices/microservices.md
- src/manual/design/devel/best-practices/testing.md
This is intended as  pretty straightforward interpretation of what was presented in https://github.com/taskcluster/taskcluster-rfcs/pull/110
> Bug 1446966 - [RFC 0110] Document Testing BP's

- src/manual/using/actions/spec.md
- src/manual/using/actions/ui.md
(with some minor formatting fixes)
> Bug 1415868 - ownTaskId and task are not provided for kind=hook

- layout/schema.pug
- lib/raw.js
- lib/render-schemas.js
This isn't perfect, but it is better than nothing!
> Fix inifite loop in schemas

- src/tutorial/debug-task.md
Picked the brains of dustin, jonasfj, and bstack in #taskcluster and
incorporated their feedback to bring the section more in line with how TC
actually works right now, and try to make it answer my own questions that I
have as a noob to debugging.
> Update debugging docs

- lib/navlinks.js
- lib/raw.js
The second commit is the bug fix here; the first is (IMHO) an improvement all the same.
> Bug 1452776 - be careful about special-casing 'docs'

- src/manual/using/actions/spec.md
> Bug 1476576 - add more detail to hooks kind

- src/resources.md
> Bug 1489156 - add bugzilla and codetribute to resources

- src/manual/design/apis/reference-format.md
I'm not sure those schema links will work.  We'll find out..
> Bug 1476786 - update manual regarding API references to include rootUrls

- src/manual/using/administration.md
> Add ACL guidelines to administration doc

- src/manual/design/env-vars.md
@SimonSapin does this look better?
> Bug 1511457 - be a bit clearer about where vars are used and provided
