taskcluster/taskcluster-docs

docker-worker/index.md
While reading, I saw this one word may want to be linux instead of linix.
=> upd : docker-worker/index.md : linux typo

workers/generic-worker/index.md
Relocated github.com/petemoore/generic-worker => github.com/taskcluster/generic-worker
This PR is for the master branch, will raise another one for gh-pages branch.
=> petemoore/generic-worker => taskcluster/generic-worker

_config.yml, introduction/getting-started/index.md
This includes some Mozilla-specific information to help other Mozilla users to situate TC within its environment.  If you have a better suggestion for how to make Mozilla-specific bits accessible to Mozillians while still keeping taskcluster generic, I'm all ears.
=> Add a getting-started guide

presentations/scopes/index.html
This keeps the X/Y order the same by using the passive voice ("is
satisfied by"), and includes a simple categorical at the bottom of the
example slides: required scopes are satisfied by possessed scopes.
=> Clarify satisfyability a little bit

introduction/getting-started/index.md
which is the taskGraphId (but only for task-graphs)... anyways no need to say that here...
=> Think it should say taskGroupId

_config.yml
Seems reasonable to have the Blog from our main site - e.g. like https://golang.org/ does.
=> Added a link to Planet Taskcluster blog

workers/docker-worker/index.md
I went in to write about relengAPIProxy but found some other stuff to fix, too
=> update feature documentation

_config.yml
We have no easy standard way to track open PRs/Issues - with this dashboard link, you quickly can keep track of what is currently open and needs attention.
=> Added a link to open issues and pull requests on github

devel/namespaces/index.md
This puts some order on the namespace of clientIds.
I updated https://bugzilla.mozilla.org/show_bug.cgi?id=1248575 and https://bugzilla.mozilla.org/show_bug.cgi?id=1248574 accordingly.
=> Describe clientId namespace

devel/namespaces/index.md
A few changes, but the `project-member:<project>` one is the one I'm particularly interested in getting feedback on.
=> Login v3 updates

introduction/getting-started/index.md, learn/authenticate/index.md, learn/create-task/index.md, presentations/TC-101/slides/what-is-tc.md, presentations/TC-102/slides/tc-clients/08.md, presentations/scopes/index.html
This avoids privileging the b2gtest workerType, which new users do not
have access to and which anyway may go away someday.
=> Use tutorial instead of b2gtest

README.md, _config.yml
I've done this since GitHub Pages is dropping support for Redcarpet.
See https://github.com/blog/2100-github-pages-jekyll-3
I've tested that all the extensions we had enabled in Redcarpet also work in kramdown. This is true for all except [`:autolink`](https://github.com/vmg/redcarpet/blob/v3.2.2/README.markdown#and-its-like-really-simple-to-use). However, searching our markdown files, there were no absolute urls in the text that were taking advantage of this feature, so there was no markdown to update.
=> Switched from redcarpet to kramdown

_layouts/default.html, assets/docsearch.css
This integrates [DocSearch](https://community.algolia.com/docsearch/documentation/). Our site will get indexed every 24 hours. We can make this fit in the navbar a bit nicer later if we want, but I think it works pretty well for now.
=> Add docsearch

layout/head.pug, src/assets/docref/docref.js, src/assets/docson/docson.js
This hacks the local copy of docson, as well as the bits of code parsing
data-doc-ref and data-doc-schema, to always load from https URLs, even
if the given URL is http.  This assumes that
https://schemas.taskcluster.net and https://references.taskcluster.net
are the same as their non-https cousins, and that all ref/schema URLs
are from one of those two sites.
---
@bstack, @jonasfj this works for me locally via ngrok, and I've deployed it to https://docs.taskcluster.net for testing.  The result seems to be working fine.
=> Convert http to https URLs

layout/head.pug, layout/navbar.pug, src/assets/docsearch.css
Turns out they accidentally disabled us. We've been indexed again and our new docs structure works much more nicely with their search as well!
=> Add search back

layout/head.pug, src/assets/docreadme/docreadme.js, src/reference/core/aws-provisioner/index.md
This PR implements a new attribute `data-doc-readme` for doc markdown which makes a page download an md file from a url and renders it to html.
It was only applied to the aws-provisioner main page to get some feedback. Once the approach is approved, we will move on to the rest of the items in the table of contents.
=> create readme docs for aws-provisioner

src/reference/core/cors-proxy/readme.md, src/reference/core/github/index.md, src/reference/core/hooks/index.md, src/reference/core/index.md, src/reference/core/index/index.md, src/reference/core/login/index.md, src/reference/core/purge-cache/index.md, src/reference/core/secrets/index.md, src/reference/index.md, src/reference/platform/auth/index.md, src/reference/platform/index.md, src/reference/platform/queue/index.md, src/reference/platform/scheduler/index.md
This just extends your work to the rest of our services. cors-proxy already had an `index.md` so I just put it in `readme.md`.
=> Add readmes for all of our services

src/reference/platform/queue/task.md
I often go looking for this, and probably others don't know to find it
under the createTask API method.
=> Add a task definition as a separate page

src/assets/docreadme/docreadme.js
Cors-proxy is being added to the data-doc-readme processor. It now uses cors-proxy.
=> use cors-proxy for github readme

src/manual/devel/namespaces.md
Note, I couldn't get to run locally (problem with `npm install`) so I haven't tested locally. But it is just a wording change.
=> Clarified naming convention for repository based secrets

layout/followup.pug, layout/layout.pug, src/tutorial/async-javascript.md, src/tutorial/authenticate.md, src/tutorial/create-task-via-api.md, src/tutorial/gecko-decision-task.md, src/tutorial/gecko-task-graph.md, src/tutorial/gecko-tasks.md, src/tutorial/hack-tc.md, src/tutorial/hello-world.md, src/tutorial/index.md, src/tutorial/interactive.md, src/tutorial/what-is-tc.md
This was motivated by me wanting the links at the bottom of the pages to be styled a bit differently, but I think the new way the links are defined is a pretty nice side-effect of this. I'm 100% up for changing some bit of how this works/looks.
Right now the links are on the [bottom of the page where they were before](https://imbstack.keybase.pub/bottom-next-steps.mov), but perhaps [the sidebar](https://imbstack.keybase.pub/sidebar-next-steps.mov) is a better place for them?
=> Structure tutorial next-steps

src/reference/core/notify/api-docs.md, src/reference/core/notify/index.md
Since http://references.taskcluster.net/manifest.json now includes Notify service, I added API reference to docs site.
If we're not ready to have docs on this service yet, we probably shouldn't add it to manifest.json.
=> Added API docs for taskcluster-notify

redirects.yml
I'm not sure these URLs ever worked, but something once pointed to them,
so let's give users the content they came for.
=> add more scheduler redirects

src/manual/apis/roles.md, src/manual/execution/workers/index.md, src/tutorial/authenticate.md
There are 3 cases of links in the markdown links containing traling slashes. In
2 cases this results in broken links:
- tutorial/authenticate.md has a broken link to APIs
- manual/execution/workers/index.md has a broken link to worker interaction.
In another case this did not result in a broken link:
- manual/apis/roles.md links to namespaces.
It appears pages inside devel/ will redirect if issued at <base>/devel/page.
Which baffles me. However I figured this link should also be made consistent
with the absolute addressing used in the docs, so I've updated it.
=> Update a few inconsistent links in MD files.

src/tutorial/hello-world.md
This fixes a link which is broken due to having a traling slash, same as last
commits, but a case that I missed.
=> Fix trailing slash on link in tutorial/hellow-world.md

src/reference/core/cloud-mirror/index.md, src/reference/core/diagnostics/index.md, src/reference/core/events/index.md, src/reference/core/stats-collector/index.md, src/reference/core/statsum/index.md
Ideally this would become our authoritative list of services.
I realize this is redundant with @kristelteng's work, but it's an easy thing to merge in the interim.
=> Add README docs for more services

main.js, package.json, src/tutorial/async-javascript.md
It seems this was just included for the sake of the in-browser environment.  The gulp upload doesn't use it (or any of our own code that might be confused by its monkeypatching)
=> remove aws-sdk-promise

redirects.yml, src/tutorial/gecko-task-graph-howto.md, src/tutorial/gecko-task-graph.md
The redirects were the thing I added to try to get docs to regenerate yesterday.  They work fine on S3, but cause redirect loops with `gulp webserver`, so I guess we can leave them out.
=> Bug 1309713: add more links to gecko docs

layout/reference.pug
I believe there's a typo here. The header for output schemas should be "Response" instead of "Request Payload", which was probably overlooked during the copy-paste.
Correct me if I missed anything.
=> Fix a typo in the header of output schemas

layout/layout.pug, src/assets/style.css
Right now visiting any pages which have a sidebar navigation on mobile leaves you in a dead end; you can view the page you navigate to, but cannot choose where to go next as the sidebar has been hidden on mobile to keep from cluttering the top of the page.
To overcome this, I just added a simple "Menu" button at the top of the page on mobile to toggle the sidebar. The sidebar will continue to be visible on desktop, and mobile can open the menu as desired.
=> Rudimentary toggle-able mobile sidebar

src/manual/devel/namespaces.md
Makes it clearer that the amqp routes for indexes all start with `index.`, for those of us still learning.
=> Clarify `index.` prefix use and provide example

src/assets/style.css, src/manual/integrations/apis/3rdparty.md, src/manual/integrations/apis/authorized-scopes.md, src/manual/integrations/apis/clients.md, src/manual/integrations/apis/index.md, src/manual/integrations/apis/roles.md, src/manual/integrations/apis/scopes.md, src/manual/integrations/apis/signed-urls.md, src/manual/integrations/apis/temporary-credentials.md, src/reference/core/index.md, src/reference/libraries/index.md, src/reference/platform/index.md, src/reference/workers/index.md
And remove the CSS hack that was sort of doing this before, but actually
just hiding a lot of titles.
=> Remove duplicate page headings

src/manual/integrations/hooks.md, src/manual/tasks/decision.md
This adds a manual page for hooks, and since I referred to them, a decision task.
taskcluster/taskcluster-hooks#35 takes care of making sure hooks produce a task with taskId === taskGroupId.
=> Add a manual page for hooks, and decision tasks

gulpfile.js
Tested locally and it seems to work. I'm assuming here we don't want the images to show up in the table of contents. If that's not true, we can fix that easily as well!
=> Bug 1332775 - Include images from lib-docs in builds

src/reference/workers/generic-worker/features.md, src/reference/workers/generic-worker/payload.md
Added some docs about the new feature.
=> Bug 1287112 - chain of trust in generic worker

src/reference/libraries/docker-exec-websocket-server/index.md, src/reference/libraries/ws-shell/index.md
The name has server in it, but this seems like the best place for it?
=> Add docker-exec-websocket-server to libraries list

src/manual/devel/best-practices/scopes.md
I think we're pretty good at following this rule.. But it's worth writing down, along with it's obvious exceptions like short-live resources..
=> Clarify when to use roles vs. storing scopes

gulpfile.js, lib/userlist.js, package.json, src/assets/style.css, src/index.md, src/people.pug
This is generated using public Mozillians API data.
I'm working with the Mozillians folks to find a better way to filter only public data, and I haven't set up the automatic builds yet, but I'll figure that out before I merge.  In the interim, if you want to see the results, you'll need to run it locally with your own Mozilians API key in `$MOZILLIANS_API_KEY`.
Note that a *lot* of the accounts this links to are non-public.  I was thinking of reaching out to the relevant people to let them know (a) you're in the credits and (b) private is fine, but if you want more detail included, consider making your profile public.
=> Add a "people of taskcluster" page to the docs

layout/layout.pug
On smaller screens, the content was overlapping with the menu list (you'll need the dev-tools inspector to see the overlap). This fixes the issue
=> Bug 1390350 - Can't click menu items when window is too narrow

src/manual/using/integration/backend.md, src/manual/using/integration/frontend.md, src/manual/using/integration/guidelines.md
* rewrite frontend docs to outline the new process and refer to tc-login
* move guidelines into a separate docs
* remove references to the old way
=> Bug 1395345 - update docs to cover using OIDC

src/manual/using/caching.md
The idea is to say "hey, caching can be good!" and give pointers to the implementations.
We don't yet have any online documentation for taskcluster-workers.  I expect eventually we'll direct people to the documentation in the worker type tool.
=> add a manual section on caching

src/manual/design/namespaces.md
Future use-case might be QEMU images... I want to embed this convention in the in-tree code for managing QEMU images...
So private images might be `repo/hg.mozilla.org/mozilla-central/qemu-images/image.tar.zst` on a task in the index...
=> pattern for private artifacts for repositories

gulpfile.js, util/taskcluster-build.sh
The idea is to modify the hook to pass "hook" instead of "push" once this lands.
=> Force publishing on push

src/manual/design/apis/hawk/clients.md, src/manual/design/apis/hawk/roles.md, src/manual/design/apis/hawk/scopes.md
This detail is [now included](https://github.com/taskcluster/taskcluster-auth/pull/113) in the tc-auth reference pages, closer to
where it is implemented.
=> Remove some detail on clients, scopes, roles

src/manual/design/apis/hawk/temporary-credentials.md
This is now taken care of in the auth service directly:
https://github.com/taskcluster/taskcluster-auth/pull/117
=> Document that temp credentials require no clock drift adjustment

gulpfile.js
I believe this will fix our woes with s3 being filled with cruft.
=> Sync files with s3 and skip cacheing since we don't use it anyway

src/manual/using/actions/guidelines.md, src/manual/using/actions/schema.yml, src/manual/using/actions/spec.md, src/manual/using/actions/ui.md
You might want to take this commit-by-commit.
Mostly I'd like some thought and feedback on the security implications.  The risk is that someone makes a try job with the `retrigger` action configured to run hook `project-gecko/in-tree-action-3-relpromo` with a payload that promotes some malicious try build as Firefox 666.  Then some innocent test task turns orange on the try job and they kindly ask someone in releng or relman to click "retrigger" for that task.
My thinking is that a "generic" actions UI would run the user through two dialogs for an hook action:
* Enter the task input so that it matches the schema
* See and confirm the hookId, hookGroupId, and rendered payload
The first can be skipped if there's no schema, of course.
Treeherder, however, can do a bit better:
* Use …
=> Bug 1415868 - docs for actions with kind=hook

src/manual/design/namespaces.md, src/manual/using/administration.md
The idea with `project-grants:<project>/<grantName>` is that the
project admins can't modify the role. Yet, they assume all these
roles via. a grant of `assume:project-grants:<..>/*` in `project-admin:*`.
This ensures that project admins can't modify the description of why
these scopes were granted to them. Also they can't accidentally delete
them.
It also makes it easy to list all the scopes we've granted to projects
that aren't part of the scopes normally granted to projects.
I propose that `grantName` is something descriptive, and that each grant
can contain multiple scopes. For example I create `project-grants:meao/github-repos`
that grants scopes like: `auth:{create|modify|delete}-role:repo:github.com/mozilla-more/*`.
=> Introduce project-grants

src/manual/design/devel/best-practices/testing.md
I ran into this when thinking about how to test tc-login against auth0.  I don't think Mozilla has an environment that would allow it.  So there's no way to provide secrets, meaning that mockSuite will complain if NO_TEST_SKIP is set.  It's much simpler to just not try to *write* tests which would never run anyway.
=> Don't use mockSuite with expensive tests

lib/raw.js, lib/render-schemas.js
This was hard to track down because the API docs [do not make it clear that you can pass a base URI](https://github.com/BigstickCarpet/json-schema-ref-parser/issues/91).
This also hacks around the poor error handling (every time I try to actually solve it I get lost trying to figure out which streams API which libraries implement..) and serializes the ref processing so that failures don't happen concurrently with successes.
=> Bug 1471205 - fix handling of relative $ref's

lib/raw.js
This is truly a mess, between old and new services.  I think a better
way to handle this would be to load all schemas -- everywhere -- and
index them by abstract $id, then dereference them.  But that sort of
load-everything approach is difficult and error-prone in gulp.
=> Bug 1472802 - for api schemas, always use local copies

src/manual/index.md
If the link ends with a slash server is responding with a 404 error.
For `/docs/manual/using/` it's looking for
`/docs/manual/using/index.html` which doesn't exist.
This could be a server configuration issue, but it can be fixed with
this patch as well.
=> Link to `Using Taskcluster` page responds with a 404.

src/assets/style.css, src/tutorial/gecko-new-job.md
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1507638 and also allows things to build again.
=> Bug 1507638
